In [1]:
import numpy as np

1. Создайте массив 10х10, заполненный в центре нулями, а по границе единицами.

In [11]:
print(np.pad(np.zeros((8,8)), 1, mode='constant', constant_values=1))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


2. Создайте массив 8х8, заполненный 0 и 1 в шахматном порядке.

In [14]:
print(np.tile(np.array([[0,1], [0,1]]), (4,4)))

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


3. Создайте матрицу 5x5 со значениями 1,2,3,4 под главной диагональю. Остальные значения - нули

In [15]:
print(np.diagflat([1, 2, 3, 4], k=-1))

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


4. Создайте случайный массив 5х5 и нормируйте его так, чтобы среднее вдоль каждой строки было равно нулю.

In [43]:
arr = np.random.rand(5, 5)
print(arr - np.mean(arr, axis=1).reshape(5,1))

[[-0.13665058 -0.13748109  0.21686617  0.09526808 -0.03800257]
 [ 0.35553463 -0.28968485 -0.15312311  0.33187891 -0.24460558]
 [ 0.40570137  0.37435424 -0.29750633 -0.50324034  0.02069105]
 [ 0.36153107  0.29440912 -0.37266962  0.11780861 -0.40107917]
 [-0.38176436  0.46102772  0.05967239  0.2018546  -0.34079034]]


5. Создайте двумерный массив 10x3, заполненный случайными числами от 0 до 1. В каждой строке выберите значение, наиболее близкое к 0.5.

In [48]:
arr = np.random.rand(10,3)
print(arr)
print(arr[np.arange(10), np.argmin(np.abs(arr - 0.5), axis=1)])

[[0.32500489 0.73741785 0.27863184]
 [0.87022141 0.59505786 0.35760422]
 [0.90900179 0.55415758 0.08528503]
 [0.81315668 0.4428755  0.25958269]
 [0.98746616 0.71550183 0.59603849]
 [0.92670315 0.2019394  0.71372802]
 [0.87386315 0.65711583 0.52282008]
 [0.67905757 0.76436829 0.74524023]
 [0.32887384 0.28829047 0.79253626]
 [0.06432803 0.33509256 0.52763867]]
[0.32500489 0.59505786 0.55415758 0.4428755  0.59603849 0.71372802
 0.52282008 0.67905757 0.32887384 0.52763867]


6. Создайте двумерный массив 6x6, заполненный случайными значениями. Сумму по каждой строке поделите на максимальный элемент из столбца с тем же индексом.

In [50]:
arr = np.random.rand(6,6)
print(arr)
print(arr.sum(axis=1) / arr.max(axis=0))

[[0.00875869 0.1967461  0.2532242  0.64682216 0.23730066 0.17583908]
 [0.26731562 0.32796046 0.14468295 0.08480944 0.21463494 0.22448952]
 [0.63771486 0.24699998 0.58272212 0.27588301 0.25132532 0.98732026]
 [0.2044862  0.1040627  0.92898053 0.11850211 0.52639494 0.8242304 ]
 [0.18484845 0.07111427 0.77717145 0.39392031 0.76661417 0.24742086]
 [0.10346182 0.18195402 0.19834269 0.96066468 0.44058092 0.03512742]]
[2.38145757 3.85379663 3.2099333  2.81748348 3.18424784 1.94479101]


7. На примере массива x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) найдите максимальный элемент в массиве среди элементов, перед которыми стоит ноль.

In [52]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(x[1:][x[:-1] == 0].max())

5


8. Пусть заданы два массива x = np.ones(10) и i = np.array([0, 1, 2, 3, 5, 5, 5, 8]). Прибавьте единицу к тем элементам массива x, индексы которых указаны в массиве i. В случае, если некоторый индекс встретился в массиве i несколько раз, прибавьте к соответствующему элементу массива x число вхождений данного индекса в массив i.

In [59]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])

print(x + np.bincount(i, minlength = 10))

[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


9. Задайте два массива a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]]) и b = np.array([3, 5, 10, 0]). Создайте массив, в котором каждый элемент первого массива заменен на ближайший к нему элемент второго массива.

In [61]:
a = np.array([[1, 4.9, 2.4], [7.1, 7, 9.8], [2, 4.6, 1.2]])
b = np.array([3, 5, 10, 0])

print(b[np.argmin(np.abs(a[:, :, None] - b), axis=2)])

[[ 0  5  3]
 [ 5  5 10]
 [ 3  5  0]]


10. Найдите скользящие средние с окном размера 3 по массиву a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2]).

In [63]:
a = np.array([1, 4.9, 2.4, 7.1, 7, 9.8, 2, -5, 4.6, 1.2])

print((a[:-2] + a[1:-1] + a[2:]) / 3)

[2.76666667 4.8        5.5        7.96666667 6.26666667 2.26666667
 0.53333333 0.26666667]
